/* CipherBridge site_early_hook — Playwright init_script only */
/* 站点增量；通用 CDP 已在 stealth 底座（此处再带一份幂等兜底） */
(function(){try{if(window.__cbCdpConsolePatched)return;window.__cbCdpConsolePatched=1;var c=console;if(!c)return;['log','debug','info','warn','error'].forEach(function(k){var o=c[k];if(typeof o!=='function')return;c[k]=function(){var a=[].slice.call(arguments);for(var i=0;i<a.length;i++){if(a[i]instanceof Error)a[i]=String(a[i]);}return o.apply(c,a);};});}catch(e){}})();
try{
(function(){try{var W=window,D=Object.getOwnPropertyDescriptor,T=Function.prototype.toString;var nat="function () { [native code] }";function mkNative(f,name){try{var s='function '+(name||f.name||'')+'() { [native code] }';Object.defineProperty(f,'name',{value:name||f.name||'',configurable:true});Object.defineProperty(f,'toString',{value:function(){return s},configurable:true,writable:true})}catch(e){}return f}if(!W.__fpScannerGuard){W.__fpScannerGuard=1;try{delete W.__pwInitScripts;delete W.__playwright__binding__;delete W.__pwInitScripts}catch(e){}
var np=W.Navigator&&Navigator.prototype;if(np){try{var d=D(np,'webdriver');if(!d){Object.defineProperty(np,'webdriver',{get:function(){var ua=navigator.userAgent||'';return /HeadlessChrome/.test(ua)?undefined:false},set:undefined,configurable:true,enumerable:true})}}catch(e){}try{if(Object.prototype.hasOwnProperty.call(navigator,'webdriver'))delete navigator.webdriver}catch(e){}
try{var d2=D(navigator,'webdriver');if(!d2||d2.get||d2.set){delete navigator.webdriver;Object.defineProperty(navigator,'webdriver',{get:function(){return false},configurable:true,enumerable:true})}}catch(e){}}
try{var orig=T;var toString=function(){try{if(this&&typeof this.__fpNative==='string')return this.__fpNative;return orig.apply(this,arguments)}catch(e){return orig.apply(this,arguments)}};mkNative(toString,'toString');toString.__fpNative=nat;Function.prototype.toString=toString;Object.defineProperty(Function.prototype,'toString',{value:toString,writable:true,configurable:true,enumerable:false});var cbs={console:W.console};
if(cbs.console){['log','info','warn','error','debug','trace'].forEach(function(k){try{var o=cbs.console[k];if(typeof o!=='function')return;var w=function(){var a=Array.prototype.slice.call(arguments);for(var i=0;i<a.length;i++){if(a[i]&&a[i].constructor&&a[i].constructor.name==='Error'&&a[i].stack)a[i]=String(a[i].stack)}return o.apply(cbs.console,a)};mkNative(w,k);cbs.console[k]=w}catch(e){}})}}catch(e){}
try{var gc=W.OffscreenCanvas;var getp=null;function patchGL(P){if(!P||P.__fpGL)return;try{var gp=P.getParameter;if(typeof gp!=='function')return;var nw=function(p){var r=gp.apply(this,arguments);try{if(p===0x9245||p===0x9246){var s=String(r);if(/swiftshader|llvmpipe|software|basic render|microsoft basic/i.test(s)){return p===0x9245?'Intel Inc.':'Intel(R) UHD Graphics 620'}}}catch(e){}return r};mkNative(nw,'getParameter');nw.__fpNative=nat;Object.defineProperty(nw,'__fpGL',{value:true});P.getParameter=nw}catch(e){}}patchGL(W.WebGLRenderingContext&&WebGLRenderingContext.prototype);patchGL(W.WebGL2RenderingContext&&WebGL2RenderingContext.prototype);try{if(W.Worker){var OW=W.Worker;var NW=function(a,b){try{if(typeof a==='string')return new OW(a,b);if(W.Blob&&a instanceof W.Blob)return new OW(a,b)}catch(e){}return new OW(a,b)};mkNative(NW,'Worker');W.Worker=NW}}catch(e){}}catch(e){}
try{var ep=W.EventTarget&&EventTarget.prototype;if(ep&&typeof ep.addEventListener==='function'&&!ep.__fpNative2){var oe=ep.addEventListener;var ne=function(){return oe.apply(this,arguments)};ne.__fpNative=nat;mkNative(ne,'addEventListener');EventTarget.prototype.addEventListener=ne}}catch(e){}}catch(e){}})();
}catch(e){try{console.warn('[CipherBridge] site_early_hook',e);}catch(_){}}
